server:
  port: 8761

spring:
  application:
    name: ts-service-registry
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16

eureka:
  instance:
    hostname: ts-service-registry
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://ts-service-registry:8761/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
