apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-service-registry-deployment
  labels:
    app: ts-service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-service-registry
  template:
    metadata:
      labels:
        app: ts-service-registry
    spec:
      containers:
        - name: ts-service-registry
          image: tinystepsd3v/ts-service-registry # CORRECTED: Placeholder name now matches ci.yml
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8092
